Twilight Princess Randomizer [GC]: externals/libtp_rel/source/cxx.cpp File Reference
cxx.cpp File Reference
#include <cstring>
#include "tp/JKRExpHeap.h"
#include "tp/m_do_ext.h"
Functions
void * operator new (std::size_t size)
void * operator new[] (std::size_t size)
void operator delete (void *ptr)
void operator delete[] (void *ptr)
void operator delete (void *ptr, std::size_t size)
void operator delete[] (void *ptr, std::size_t size)
Function Documentation
operator delete() [1/2]
void operator delete (void * ptr)
Definition at line 18 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     return libtp::tp::jkr_exp_heap::do_free_JKRExpHeap( archiveHeapPtr, ptr );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_free_JKRExpHeap().
operator delete() [2/2]
void operator delete (void * ptr, std::size_t size)
Definition at line 28 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     return libtp::tp::jkr_exp_heap::do_free_JKRExpHeap( archiveHeapPtr, ptr );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_free_JKRExpHeap().
operator delete[]() [1/2]
void operator delete[] (void * ptr)
Definition at line 23 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     return libtp::tp::jkr_exp_heap::do_free_JKRExpHeap( archiveHeapPtr, ptr );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_free_JKRExpHeap().
operator delete[]() [2/2]
void operator delete[] (void * ptr, std::size_t size)
Definition at line 33 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     return libtp::tp::jkr_exp_heap::do_free_JKRExpHeap( archiveHeapPtr, ptr );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_free_JKRExpHeap().
operator new()
void* operator new (std::size_t size)
Definition at line 6 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     void* newPtr = libtp::tp::jkr_exp_heap::do_alloc_JKRExpHeap( archiveHeapPtr, size, 0x20 );
     return memset( newPtr, 0, size );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_alloc_JKRExpHeap().
operator new[]()
void* operator new[] (std::size_t size)
Definition at line 12 of file cxx.cpp.
 {
     void* archiveHeapPtr = libtp::tp::m_Do_ext::archiveHeap;
     void* newPtr = libtp::tp::jkr_exp_heap::do_alloc_JKRExpHeap( archiveHeapPtr, size, 0x20 );
     return memset( newPtr, 0, size );
 }
References libtp::tp::m_Do_ext::archiveHeap, and libtp::tp::jkr_exp_heap::do_alloc_JKRExpHeap().