Twilight Princess Randomizer [GC]: libtp::tp::d_save Namespace Reference
libtp::tp::d_save Namespace Reference
Functions
uint16_t getRupeeMax ()
void getSave (d_com_inf_game::GameInfo *gameInfoPtr, int32_t areaID)
Sets the current AreaNode for region-specific flags by loading it from the ScratchPad/QuestLog.
void putSave (d_com_inf_game::GameInfo *gameInfoPtr, int32_t areaID)
Puts the previously set AreaNode for region-specific flags back into the ScratchPad/QuestLog.
void onEventBit (uint16_t flag)
Sets an eventBit for the currently active save.
void offEventBit (uint16_t flag)
Unsets an eventBit for the currently active save.
Function Documentation
getRupeeMax()
uint16_t libtp::tp::d_save::getRupeeMax ()
@brief Gets the maximum number of rupees
Warning! If this function is manipulated to return a higher number than
what the HUD can display (4 digits base 10) it causes serious issues (e.g. random crashes)
@return Returns the maximum number of rupees Link can hold in his
current wallet
Referenced by mod::game_patch::patchWallet().
getSave()
void libtp::tp::d_save::getSave (d_com_inf_game::GameInfo * gameInfoPtr, int32_t areaID)
Sets the current AreaNode for region-specific flags by loading it from the ScratchPad/QuestLog.
For more information about AreaNodes please refer to https://docs.google.com/spreadsheets/d/1OvlqH_OG_svcLZfuSDBjCLHFivcsBGpOD25o-_6vblA/edit#gid=0
Parameters
gameInfoPtr Pointer to d_com_inf_game::gameInfo
areaID ID of the current Area
Referenced by mod::rando::Seed::applyRegionFlags().
offEventBit()
void libtp::tp::d_save::offEventBit (uint16_t flag)
Unsets an eventBit for the currently active save.
Parameters
flag Offset+Flag
onEventBit()
void libtp::tp::d_save::onEventBit (uint16_t flag)
Sets an eventBit for the currently active save.
Parameters
flag Offset+Flag
putSave()
void libtp::tp::d_save::putSave (d_com_inf_game::GameInfo * gameInfoPtr, int32_t areaID)
Puts the previously set AreaNode for region-specific flags back into the ScratchPad/QuestLog.
For more information about AreaNodes please refer to https://docs.google.com/spreadsheets/d/1OvlqH_OG_svcLZfuSDBjCLHFivcsBGpOD25o-_6vblA/edit#gid=0
Parameters
gameInfoPtr Pointer to d_com_inf_game::gameInfo
areaID ID of the current Area
Referenced by mod::rando::Seed::applyRegionFlags().