Twilight Princess Randomizer [GC]: externals/libtp_rel/source/rel.cpp File Reference
rel.cpp File Reference
Namespaces
mod
Typedefs
typedef void(* PFN_voidfunc) ()
Functions
__attribute__ ((section(".ctors"))) extern PFN_voidfunc _ctors_start[]
__attribute__ ((section(".dtors"))) extern PFN_voidfunc _dtors_start[]
void _prolog ()
void _epilog ()
void _unresolved ()
void mod::main ()
Typedef Documentation
PFN_voidfunc
typedef void(* PFN_voidfunc) ()
Definition at line 3 of file rel.cpp.
Function Documentation
__attribute__() [1/2]
__attribute__ ((section(".ctors")))
Referenced by _prolog().
__attribute__() [2/2]
__attribute__ ((section(".dtors")))
Referenced by _epilog().
_epilog()
void _epilog ()
Definition at line 29 of file rel.cpp.
 {
     // In the unlikely event we ever get here, run the global destructors
     for ( PFN_voidfunc* dtor = _dtors_start; dtor != _dtors_end && *dtor; ++dtor )
     {
         ( *dtor )();
     }
 }
References __attribute__().
_prolog()
void _prolog ()
Definition at line 18 of file rel.cpp.
 {
     // Run global constructors
     for ( PFN_voidfunc* ctor = _ctors_start; ctor != _ctors_end && *ctor; ++ctor )
     {
         ( *ctor )();
     }
     // Run main
     mod::main();
 }
References __attribute__(), and mod::main().
_unresolved()
void _unresolved (void)
Definition at line 38 of file rel.cpp.
 {}