Twilight Princess Randomizer [GC]: mod::events Namespace Reference
mod::events Namespace Reference
Functions
void onLoad (rando::Randomizer *randomizer)
Runs when loading just started.
void offLoad (rando::Randomizer *randomizer)
Runs when loading just finished.
void onDZX (rando::Randomizer *randomizer, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo)
Runs when one of the DZX init functions run.
Function Documentation
offLoad()
void mod::events::offLoad (rando::Randomizer * randomizer)
Runs when loading just finished.
Parameters
randomizer Pointer to mod::randomizer
Definition at line 19 of file events.cpp.
 { return; }
Referenced by mod::handle_fapGm_Execute().
onDZX()
void mod::events::onDZX (rando::Randomizer * randomizer, libtp::tp::dzx::ChunkTypeInfo * chunkTypeInfo)
Runs when one of the DZX init functions run.
Parameters
randomizer Pointer to mod::randomizer
chunkTypeInfo ChunkTypeInfo of DZX entries
Definition at line 21 of file events.cpp.
     {
         if ( randomizer )
         {
             randomizer->replaceDZX( chunkTypeInfo );
         }
     }
References mod::rando::Randomizer::replaceDZX().
Referenced by mod::hookFunctions().
onLoad()
void mod::events::onLoad (rando::Randomizer * randomizer)
Runs when loading just started.
Parameters
randomizer Pointer to mod::randomizer
Definition at line 11 of file events.cpp.
     {
         if ( randomizer )
         {
             randomizer->onStageLoad();
         }
     }
References mod::rando::Randomizer::onStageLoad().
Referenced by mod::handle_fapGm_Execute().