Twilight Princess Randomizer [GC]: mod::game_patch Namespace Reference
mod::game_patch Namespace Reference
Typedefs
typedef void(* GamePatch) (bool set)
Defines a game_patch function.
Functions
void patchWallet (bool set)
Sets new limits to your wallet.
Variables
GamePatch patches [1] = { patchWallet }
Typedef Documentation
GamePatch
typedef void(* mod::game_patch::GamePatch) (bool set)
Defines a game_patch function.
Parameters
set If true we apply the patch, otherwise restore original behavior
Definition at line 23 of file game_patch.h.
Function Documentation
patchWallet()
void mod::game_patch::patchWallet (bool set)
Sets new limits to your wallet.
Patched: 1000, 5000, 9999 Unpatched: 300, 600, 1000
Definition at line 17 of file 00_wallet.cpp.
     {
         using namespace libtp;
         mod::console << "WalletPatch [" << ( set ? 'x' : ' ' ) << "]\n";
         uint32_t getRupeeMaxPtr = reinterpret_cast<uint32_t>( &tp::d_save::getRupeeMax );
         uint32_t setWalletMaxNumPtr = reinterpret_cast<uint32_t>( &tp::d_menu_collect::setWalletMaxNum );
         uint16_t values[3] = { 1000, 5000, 9999 };
         if ( !set )
         {
             values[0] = 300;
             values[1] = 600;
             values[2] = 1000;
         }
         // 300 -> 1000
         *reinterpret_cast<uint32_t*>( getRupeeMaxPtr + 0x30 ) = ASM_LOAD_IMMEDIATE( 3, values[0] );
         // 600 -> 5000
         *reinterpret_cast<uint32_t*>( getRupeeMaxPtr + 0x38 ) = ASM_LOAD_IMMEDIATE( 3, values[1] );
         // 1000 -> 9999 (> 4 digit not good)
         *reinterpret_cast<uint32_t*>( getRupeeMaxPtr + 0x40 ) = ASM_LOAD_IMMEDIATE( 3, values[2] );
         // 600 -> 5000
         *reinterpret_cast<uint32_t*>( setWalletMaxNumPtr + 0x18 ) = ASM_COMPARE_WORD_IMMEDIATE( 0, values[0] );
         // 300 -> 1000
         *reinterpret_cast<uint32_t*>( setWalletMaxNumPtr + 0x24 ) = ASM_COMPARE_WORD_IMMEDIATE( 0, values[1] );
         // 1000 -> 9999
         *reinterpret_cast<uint32_t*>( setWalletMaxNumPtr + 0x30 ) = ASM_COMPARE_WORD_IMMEDIATE( 0, values[1] );
         // Update the cache
         gc::os_cache::DCFlushRange( reinterpret_cast<void*>( getRupeeMaxPtr ), 0x41 );
         gc::os_cache::ICInvalidateRange( reinterpret_cast<void*>( getRupeeMaxPtr ), 0x41 );
         gc::os_cache::DCFlushRange( reinterpret_cast<void*>( setWalletMaxNumPtr ), 0x31 );
         gc::os_cache::ICInvalidateRange( reinterpret_cast<void*>( setWalletMaxNumPtr ), 0x31 );
     }
References mod::console, libtp::gc::os_cache::DCFlushRange(), libtp::tp::d_save::getRupeeMax(), libtp::gc::os_cache::ICInvalidateRange(), and libtp::tp::d_menu_collect::setWalletMaxNum().
Variable Documentation
patches
GamePatch mod::game_patch::patches = { patchWallet }
Definition at line 14 of file game_patch.cpp.
Referenced by mod::rando::Seed::applyPatches().