Twilight Princess Randomizer [GC]: libtp::patch Namespace Reference
libtp::patch Namespace Reference
Functions
void writeBranch (void *ptr, void *destination)
void writeBranchLR (void *ptr, void *destination)
void writeBranchMain (void *ptr, void *destination, uint32_t branch)
template<typename Func , typename Dest >
Func hookFunction (Func function, Dest destination)
template<typename Func >
Func unhookFunction (Func trampoline)
Function Documentation
hookFunction()
template<typename Func , typename Dest > Func libtp::patch::hookFunction (Func function, Dest destination)
Definition at line 21 of file patch.h.
     {
         uint32_t* instructions = reinterpret_cast<uint32_t*>( function );
         uint32_t* trampoline = new uint32_t[2];
         // Original instruction
         trampoline[0] = instructions[0];
         memory::clear_DC_IC_Cache( &trampoline[0], sizeof( uint32_t ) );
         // Branch to original function past hook
         writeBranch( &trampoline[1], &instructions[1] );
         // Write actual hook
         writeBranch( &instructions[0], reinterpret_cast<void*>( static_cast<Func>( destination ) ) );
         return reinterpret_cast<Func>( trampoline );
     }
Referenced by mod::hookFunctions().
unhookFunction()
template<typename Func > Func libtp::patch::unhookFunction (Func trampoline)
Definition at line 41 of file patch.h.
     {
         if ( !trampoline )
         {
             return nullptr;
         }
         uint32_t* instructions = reinterpret_cast<uint32_t*>( trampoline );
         // Restore the original instruction
         uint32_t instructionAddress = reinterpret_cast<uint32_t>( &instructions[1] );
         uint32_t branchInstruction = instructions[1];
         uint32_t branchLength;
         uint32_t* address;
         if ( branchInstruction >= 0x4A000000 )
         {
             // Branch is negative
             branchLength = 0x4C000000 - branchInstruction;
             address = reinterpret_cast<uint32_t*>( instructionAddress - branchLength - 0x4 );
         }
         else
         {
             // Branch is positive
             branchLength = branchInstruction - 0x48000000;
             address = reinterpret_cast<uint32_t*>( instructionAddress + branchLength - 0x4 );
         }
         *address = instructions[0];
         // Clear the cache for both the address and where the instructions were stored
         memory::clear_DC_IC_Cache( address, sizeof( uint32_t ) );
         memory::clear_DC_IC_Cache( instructions, sizeof( uint32_t ) );
         // Free the memory used by the trampoline
         delete[] instructions;
         return nullptr;
     }
writeBranch()
void libtp::patch::writeBranch (void * ptr, void * destination)
Definition at line 9 of file patch.cpp.
     {
         uint32_t branch = 0x48000000;     // b
         writeBranchMain( ptr, destination, branch );
     }
References writeBranchMain().
writeBranchLR()
void libtp::patch::writeBranchLR (void * ptr, void * destination)
Definition at line 15 of file patch.cpp.
     {
         uint32_t branch = 0x48000001;     // bl
         writeBranchMain( ptr, destination, branch );
     }
References writeBranchMain().
writeBranchMain()
void libtp::patch::writeBranchMain (void * ptr, void * destination, uint32_t branch)
Definition at line 21 of file patch.cpp.
     {
         uint32_t delta = reinterpret_cast<uint32_t>( destination ) - reinterpret_cast<uint32_t>( ptr );
         branch |= ( delta & 0x03FFFFFC );
         uint32_t* p = reinterpret_cast<uint32_t*>( ptr );
         *p = branch;
         memory::clear_DC_IC_Cache( ptr, sizeof( uint32_t ) );
     }
Referenced by writeBranch(), and writeBranchLR().