Twilight Princess Randomizer [GC]: libtp::gc::card Namespace Reference
libtp::gc::card Namespace Reference
Classes
struct CARDFileInfo
struct CARDStat
struct CARDBlock
Typedefs
typedef void(* CARDCallback) (int32_t chan, int32_t result)
Functions
int32_t __CARDFreeBlock (int32_t chan, uint16_t block, CARDCallback callback)
Frees the fat blocks for a specific file (This description may be incorrect)
void DeleteCallback (int32_t chan, int32_t result)
Callback to be called when a file is ready to be deleted (This description may be incorrect)
int32_t __CARDGetFileNo (void *card, const char *fileName, int32_t *fileNo)
Gets the file number of the desired file on the memory card.
int32_t CARDDeleteAsync (int32_t chan, const char *fileName, CARDCallback callback)
Deletes a file asynchronously.
int32_t CARDDelete (int32_t chan, const char *fileName)
Deletes a file synchronously.
struct libtp::gc::card::CARDFileInfo __attribute__ ((__packed__))
void CARDInit (void)
Initializes memory card API control blocks. Must be called once before using any other CARD API functions.
int32_t CARDCheck (int32_t chan)
Checks for the file system consistency of the memory card and repair it if possible.
int32_t CARDMount (int32_t chan, void *workArea, CARDCallback detachCallback)
Mounts a memory card synchronously.
int32_t CARDUnmount (int32_t chan)
Unmounts a memory card Synchronously.
int32_t CARDOpen (int32_t chan, char *fileName, CARDFileInfo *fileInfo)
Opens a file.
int32_t CARDProbeEx (int32_t chan, int32_t *memSize, int32_t *sectorSize)
This function verifies whether a memory card (of any type) is inserted in the specified slot.
int32_t CARDClose (CARDFileInfo *fileInfo)
Closes a file.
int32_t CARDRead (CARDFileInfo *fileInfo, void *addr, int32_t length, int32_t offset)
Reads data from a file synchronously.
int32_t CARDWrite (CARDFileInfo *fileInfo, void *addr, int32_t length, int32_t offset)
Writes data to a file synchronously.
void __CARDDefaultApiCallback (int32_t chan, int32_t result)
Default CARDCallback function to be used when the user did not specify one.
void __CARDSyncCallback (int32_t chan, int32_t result)
Callback function to resume the current thread after the most resent asynchronous CARD function has finished its operation.
int32_t __CARDGetControlBlock (int32_t chan, void **card)
Gets the control block for the desired memory card slot.
int32_t __CARDPutControlBlock (void *card, int32_t result)
Puts the control block for the desired memory card slot.
int32_t __CARDSync (int32_t chan)
Suspends the current thread until the most resent asynchronous CARD function has finished its operation.
int32_t __CARDUpdateFatBlock (int32_t chan, void *fatBlock, CARDCallback callback)
Updates the fat block section for a specific file on the memory card (This description may be incorrect)
void * __CARDGetDirBlock (void *card)
Gets the directly block for a specified file on the memory card (This description may be incorrect)
int32_t __CARDUpdateDir (int32_t chan, CARDCallback callback)
Updates the directly block for a specified file on the memory card (This description may be incorrect)
bool __CARDCompareFileName (void *dirBlock, const char *fileName)
Determines if the file name of the file in the current directly block is the same as the fileName parameter.
int32_t __CARDAccess (void *card, void *dirBlock)
Determines if the current file on the memory card can be accessed.
Variables
CARDBlock __CARDBlock [2]
No decent description at this time.
Typedef Documentation
CARDCallback
typedef void(* libtp::gc::card::CARDCallback) (int32_t chan, int32_t result)
Definition at line 94 of file card.h.
Function Documentation
__attribute__()
struct libtp::gc::card::CARDBlock libtp::gc::card::__attribute__ ((__packed__))
__CARDAccess()
int32_t libtp::gc::card::__CARDAccess (void * card, void * dirBlock)
Determines if the current file on the memory card can be accessed.
Parameters
card Pointer to the current card block (Struct for this not defined yet)
dirBlock Pointer the directly block for a specified file on the memory card (This description may be incorrect) (Struct for this not defined yet)
Referenced by __CARDGetFileNo().
__CARDCompareFileName()
bool libtp::gc::card::__CARDCompareFileName (void * dirBlock, const char * fileName)
Determines if the file name of the file in the current directly block is the same as the fileName parameter.
Parameters
dirBlock Pointer the directly block for a specified file on the memory card (This description may be incorrect) (Struct for this not defined yet)
fileName Internal name for the desired file on the memory card
Referenced by __CARDGetFileNo().
__CARDDefaultApiCallback()
void libtp::gc::card::__CARDDefaultApiCallback (int32_t chan, int32_t result)
Default CARDCallback function to be used when the user did not specify one.
Parameters
chan Slot number (0: slot A, 1: slot B).
result Return value of the most recent CARD function (This description may be incorrect)
Referenced by CARDDeleteAsync().
__CARDFreeBlock()
int32_t libtp::gc::card::__CARDFreeBlock (int32_t chan, uint16_t block, CARDCallback callback)
Frees the fat blocks for a specific file (This description may be incorrect)
Parameters
chan Slot number (0: slot A, 1: slot B).
block Starting block
Callback Callback function
Definition at line 7 of file card.cpp.
     {
         uint32_t card = reinterpret_cast<uint32_t>( &__CARDBlock[chan] );
         if ( *reinterpret_cast<int32_t*>( card ) == 0 )
         {
             return CARD_RESULT_NOCARD;
         }
         uint16_t cardVar = *reinterpret_cast<uint16_t*>( card + 0x10 );     // Maximum number of blocks?
         uint16_t* fatBlock = *reinterpret_cast<uint16_t**>( card + 0x88 );
         while ( block != 0xFFFF )
         {
             uint32_t tempBlock = static_cast<uint32_t>( block );
             if ( ( tempBlock < 5 ) || ( tempBlock >= cardVar ) )
             {
                 return CARD_RESULT_BROKEN;
             }
             block = fatBlock[tempBlock];
             fatBlock[tempBlock] = 0;
             fatBlock[3] += 1;
         }
         return __CARDUpdateFatBlock( chan, fatBlock, callback );
     }
References __CARDBlock, and __CARDUpdateFatBlock().
Referenced by DeleteCallback().
__CARDGetControlBlock()
int32_t libtp::gc::card::__CARDGetControlBlock (int32_t chan, void ** card)
Gets the control block for the desired memory card slot.
Parameters
chan Slot number (0: slot A, 1: slot B).
card Output for the pointer to the current card block (Struct for this not defined yet)
Referenced by CARDDeleteAsync().
__CARDGetDirBlock()
void* libtp::gc::card::__CARDGetDirBlock (void * card)
Gets the directly block for a specified file on the memory card (This description may be incorrect)
Parameters
card Pointer to the current card block (Struct for this not defined yet)
Referenced by __CARDGetFileNo(), and CARDDeleteAsync().
__CARDGetFileNo()
int32_t libtp::gc::card::__CARDGetFileNo (void * card, const char * fileName, int32_t * fileNo)
Gets the file number of the desired file on the memory card.
Parameters
card Pointer to the current card block (Struct for this not defined yet)
fileName Internal name for the desired file on the memory card
fileNo Output for the index to the desired file on the memory card
Definition at line 62 of file card.cpp.
     {
         int32_t cardIsAttached = *reinterpret_cast<int32_t*>( reinterpret_cast<uint32_t>( card ) );
         if ( cardIsAttached == 0 )
         {
             return CARD_RESULT_NOCARD;
         }
         uint32_t dirBlock = reinterpret_cast<uint32_t>( __CARDGetDirBlock( card ) );
         int32_t i;
         for ( i = 0; i < 127; i++ )
         {
             uint8_t* currentDirBlock = reinterpret_cast<uint8_t*>( dirBlock + ( i * 0x40 ) );
             if ( !__CARDCompareFileName( currentDirBlock, fileName ) )
             {
                 continue;
             }
             if ( __CARDAccess( card, currentDirBlock ) < CARD_RESULT_READY )
             {
                 continue;
             }
             *fileNo = i;
             break;
         }
         if ( i >= 127 )
         {
             return CARD_RESULT_NOFILE;
         }
         return CARD_RESULT_READY;
     }
References __CARDAccess(), __CARDCompareFileName(), and __CARDGetDirBlock().
Referenced by CARDDeleteAsync().
__CARDPutControlBlock()
int32_t libtp::gc::card::__CARDPutControlBlock (void * card, int32_t result)
Puts the control block for the desired memory card slot.
Parameters
card Pointer to the current card block (Struct for this not defined yet)
result Return value of the most recent CARD function (This description may be incorrect)
Referenced by CARDDeleteAsync(), and DeleteCallback().
__CARDSync()
int32_t libtp::gc::card::__CARDSync (int32_t chan)
Suspends the current thread until the most resent asynchronous CARD function has finished its operation.
Parameters
chan Slot number (0: slot A, 1: slot B).
Referenced by CARDDelete().
__CARDSyncCallback()
void libtp::gc::card::__CARDSyncCallback (int32_t chan, int32_t result)
Callback function to resume the current thread after the most resent asynchronous CARD function has finished its operation.
Parameters
chan Slot number (0: slot A, 1: slot B).
result Return value of the most recent CARD function (This description may be incorrect)
Referenced by CARDDelete().
__CARDUpdateDir()
int32_t libtp::gc::card::__CARDUpdateDir (int32_t chan, CARDCallback callback)
Updates the directly block for a specified file on the memory card (This description may be incorrect)
Parameters
chan Slot number (0: slot A, 1: slot B).
callback Callback function
Referenced by CARDDeleteAsync().
__CARDUpdateFatBlock()
int32_t libtp::gc::card::__CARDUpdateFatBlock (int32_t chan, void * fatBlock, CARDCallback callback)
Updates the fat block section for a specific file on the memory card (This description may be incorrect)
Parameters
chan Slot number (0: slot A, 1: slot B).
fatBlock Fat block section to be updated (Struct for this not defined yet)
callback Callback function
Referenced by __CARDFreeBlock().
CARDCheck()
int32_t libtp::gc::card::CARDCheck (int32_t chan)
Checks for the file system consistency of the memory card and repair it if possible.
Parameters
chan EXI channel number
CARDClose()
int32_t libtp::gc::card::CARDClose (CARDFileInfo * fileInfo)
Closes a file.
Parameters
fileInfo file info of the file to be closed
Referenced by libtp::tools::ReadGCI().
CARDDelete()
int32_t libtp::gc::card::CARDDelete (int32_t chan, const char * fileName)
Deletes a file synchronously.
Parameters
chan Slot number (0: slot A, 1: slot B).
fileName Internal name for the desired file on the memory card
Definition at line 144 of file card.cpp.
     {
         int32_t ret = CARDDeleteAsync( chan, fileName, __CARDSyncCallback );
         if ( ret >= CARD_RESULT_READY )
         {
             ret = __CARDSync( chan );
         }
         return ret;
     }
References __CARDSync(), __CARDSyncCallback(), and CARDDeleteAsync().
CARDDeleteAsync()
int32_t libtp::gc::card::CARDDeleteAsync (int32_t chan, const char * fileName, CARDCallback callback)
Deletes a file asynchronously.
Parameters
chan Slot number (0: slot A, 1: slot B).
fileName Internal name for the desired file on the memory card
callback Callback function to be notified of the result
Definition at line 99 of file card.cpp.
     {
         uint32_t card;
         int32_t ret = __CARDGetControlBlock( chan, reinterpret_cast<void**>( &card ) );
         if ( ret < CARD_RESULT_READY )
         {
             return ret;
         }
         int32_t fileNo;
         ret = __CARDGetFileNo( reinterpret_cast<void*>( card ), fileName, &fileNo );
         if ( ret < CARD_RESULT_READY )
         {
             __CARDPutControlBlock( reinterpret_cast<void*>( card ), ret );
             return ret;
         }
         uint32_t dirBlock = reinterpret_cast<uint32_t>( __CARDGetDirBlock( reinterpret_cast<void*>( card ) ) );
         uint32_t entry = dirBlock + ( fileNo * 0x40 );
         uint16_t* blockAddr = reinterpret_cast<uint16_t*>( entry + 0x36 );
         uint16_t* currFileBlockAddr = reinterpret_cast<uint16_t*>( card + 0xBE );
         *currFileBlockAddr = *blockAddr;
         memset( reinterpret_cast<void*>( entry ), -1, 0x40 );
         CARDCallback cb = callback;
         if ( !cb )
         {
             cb = __CARDDefaultApiCallback;
         }
         CARDCallback* cardApiCbAddress = reinterpret_cast<CARDCallback*>( card + 0xD0 );
         *cardApiCbAddress = cb;
         ret = __CARDUpdateDir( chan, DeleteCallback );
         if ( ret >= CARD_RESULT_READY )
         {
             return ret;
         }
         __CARDPutControlBlock( reinterpret_cast<void*>( card ), ret );
         return ret;
     }
References __CARDDefaultApiCallback(), __CARDGetControlBlock(), __CARDGetDirBlock(), __CARDGetFileNo(), __CARDPutControlBlock(), __CARDUpdateDir(), and DeleteCallback().
Referenced by CARDDelete().
CARDInit()
void libtp::gc::card::CARDInit (void)
Initializes memory card API control blocks. Must be called once before using any other CARD API functions.
CARDMount()
int32_t libtp::gc::card::CARDMount (int32_t chan, void * workArea, CARDCallback detachCallback)
Mounts a memory card synchronously.
Parameters
chan EXI channel number
workArea pointer to the work area to be used while a memory card is in use. The work area must be 32 byte aligned and must be larger than or equal to CARD_WORKAREA_SIZE.
detachCallback callback function to be called when the memory card is removed from the slot.
Referenced by libtp::tools::ReadGCI().
CARDOpen()
int32_t libtp::gc::card::CARDOpen (int32_t chan, char * fileName, CARDFileInfo * fileInfo)
Opens a file.
Parameters
chan EXI channel number
fileName pointer to file name to be opened
fileInfo pointer to file info to be used
Referenced by libtp::tools::ReadGCI().
CARDProbeEx()
int32_t libtp::gc::card::CARDProbeEx (int32_t chan, int32_t * memSize, int32_t * sectorSize)
This function verifies whether a memory card (of any type) is inserted in the specified slot.
The memory card size returned, in megabits, will be 4, 8, 16, 32, 64, or 128 Mb. The sector size returned, in bytes, will be 8, 16, 32, 64, or 128 KB. A game program must support memory cards whose
Parameters
chan Slot number (0: slot A, 1: slot B).
memSize Pointer to s32 object to store the memory card size, in megabits. Specify NULL if it is not necessary.
sectorSize Pointer to s32 object to store the memory card sector size, in bytes. Specify NULL if it is not necessary.
Referenced by libtp::tools::ReadGCI().
CARDRead()
int32_t libtp::gc::card::CARDRead (CARDFileInfo * fileInfo, void * addr, int32_t length, int32_t offset)
Reads data from a file synchronously.
Parameters
fileInfo file info of the file to be read
buf buffer address (32 bytes aligned)
length number of bytes to be read (multiple of CARD_READ_SIZE)
offset file position at which to start the read (multiple of CARD_READ_SIZE)
Referenced by libtp::tools::ReadGCI().
CARDUnmount()
int32_t libtp::gc::card::CARDUnmount (int32_t chan)
Unmounts a memory card Synchronously.
The work area specified by CARDMount() or CARDMountAsync() is also released. The function returns CARD_RESULT_READY if the memory card is successfully unmounted.
Parameters
chan EXI channel number
Referenced by libtp::tools::ReadGCI().
CARDWrite()
int32_t libtp::gc::card::CARDWrite (CARDFileInfo * fileInfo, void * addr, int32_t length, int32_t offset)
Writes data to a file synchronously.
Parameters
fileInfo file info of the file to be written
buf buffer address (32 bytes aligned)
length number of bytes to write. The length must be multiple of the card sector size returned by CARDGetSectorSize.
offset file position at which to start the read. The offset must be multiple of the card sector size returned by CARDGetSectorSize.
DeleteCallback()
void libtp::gc::card::DeleteCallback (int32_t chan, int32_t result)
Callback to be called when a file is ready to be deleted (This description may be incorrect)
Parameters
chan Slot number (0: slot A, 1: slot B).
result Return value of the most recent CARD function (This description may be incorrect)
Definition at line 34 of file card.cpp.
     {
         uint32_t card = reinterpret_cast<uint32_t>( &__CARDBlock[chan] );
         CARDCallback* cardApiCbAddress = reinterpret_cast<CARDCallback*>( card + 0xD0 );
         CARDCallback cb = *cardApiCbAddress;
         *cardApiCbAddress = nullptr;
         int32_t ret = result;
         if ( ret >= CARD_RESULT_READY )
         {
             uint16_t* currFileBlockAddr = reinterpret_cast<uint16_t*>( card + 0xBE );
             ret = __CARDFreeBlock( chan, *currFileBlockAddr, cb );
             if ( ret >= CARD_RESULT_READY )
             {
                 return;
             }
         }
         __CARDPutControlBlock( reinterpret_cast<void*>( card ), ret );
         if ( cb )
         {
             cb( chan, ret );
         }
     }
References __CARDBlock, __CARDFreeBlock(), and __CARDPutControlBlock().
Referenced by CARDDeleteAsync().
Variable Documentation
__CARDBlock
CARDBlock libtp::gc::card::__CARDBlock[2] extern
No decent description at this time.
Referenced by __CARDFreeBlock(), and DeleteCallback().