Twilight Princess Randomizer [GC]: libtp::display Namespace Reference
libtp::display Namespace Reference
Classes
class Console
Console wrapper class.
Functions
Console & operator<< (Console &console, const char *text)
Console & operator<< (Console &console, char *text)
Console & operator<< (Console &console, char chr)
Console & operator<< (Console &console, uint8_t n)
Console & operator<< (Console &console, int8_t n)
Console & operator<< (Console &console, uint16_t n)
Console & operator<< (Console &console, int16_t n)
Console & operator<< (Console &console, uint32_t n)
Console & operator<< (Console &console, int32_t n)
Console & operator<< (Console &console, uint64_t n)
Console & operator<< (Console &console, int64_t n)
Console & operator<< (Console &console, float n)
Console & operator<< (Console &console, void *ptr)
void clearConsole (uint8_t from, uint8_t count=0)
Clears all console lines in a given range i.e. clearConsole(0, 10)
void setConsole (bool state, uint8_t lines)
Sets the state of the console.
void setConsoleColor (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)
Sets the console background colour + Alpha.
char * print (uint8_t line, const char *text)
Copies text to a console line.
Function Documentation
clearConsole()
void libtp::display::clearConsole (uint8_t from, uint8_t count = 0)
Clears all console lines in a given range i.e. clearConsole(0, 10)
Parameters
from First line index to be cleared (inclusive)
count Number of lines to be cleared, 0 = all
Definition at line 214 of file console.cpp.
     {
         // Load the console as a local pointer to avoid loading it each loop
         tp::jfw_system::SystemConsole* console = tp::jfw_system::systemConsole;
         // If count is 0 we want to clear all lines
         std::size_t linecount = sizeof( tp::jfw_system::SystemConsole::consoleLine ) / sizeof( tp::jfw_system::ConsoleLine );
         if ( from > linecount )
         {
             from = 0;
         }
         // count = 0 ?              - remaining lines
         // from + count > linecount - remaining lines
         // else                     - count
         count = ( count == 0 ? ( linecount - from ) : ( ( from + count ) > linecount ? ( linecount - from ) : count ) );
         std::size_t lineLength = sizeof( tp::jfw_system::ConsoleLine::line );
         for ( uint8_t i = from; i < from + count; i++ )
         {
             memset( console->consoleLine[i].line, 0x0, lineLength );
         }
         return;
     }
References libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::line, and libtp::tp::jfw_system::systemConsole.
Referenced by libtp::display::Console::setLine().
operator<<() [1/13]
Console& libtp::display::operator<< (Console & console, char * text)
Definition at line 101 of file console.cpp.
     {
         console.parse( text );
         return console;
     }
operator<<() [2/13]
Console& libtp::display::operator<< (Console & console, char chr)
Definition at line 107 of file console.cpp.
     {
         char buf[1];
         buf[0] = chr;
         console.parse( buf );
         return console;
     }
operator<<() [3/13]
Console& libtp::display::operator<< (Console & console, const char * text)
Definition at line 95 of file console.cpp.
     {
         console.parse( text );
         return console;
     }
operator<<() [4/13]
Console& libtp::display::operator<< (Console & console, float n)
Definition at line 191 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         // Is there a cinttype for float?
         sprintf( buf, "%.4f", n );
         console.parse( buf );
         return console;
     }
operator<<() [5/13]
Console& libtp::display::operator<< (Console & console, int16_t n)
Definition at line 148 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId16, n );
         console.parse( buf );
         return console;
     }
operator<<() [6/13]
Console& libtp::display::operator<< (Console & console, int32_t n)
Definition at line 170 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId32, n );
         console.parse( buf );
         return console;
     }
operator<<() [7/13]
Console& libtp::display::operator<< (Console & console, int64_t n)
Definition at line 186 of file console.cpp.
     {
         return console << static_cast<int32_t>( n >> 32 ) << static_cast<int32_t>( n );
     }
operator<<() [8/13]
Console& libtp::display::operator<< (Console & console, int8_t n)
Definition at line 126 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId8, n );
         console.parse( buf );
         return console;
     }
operator<<() [9/13]
Console& libtp::display::operator<< (Console & console, uint16_t n)
Definition at line 137 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%04" PRIx16, n );
         console.parse( buf );
         return console;
     }
operator<<() [10/13]
Console& libtp::display::operator<< (Console & console, uint32_t n)
Definition at line 159 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%08" PRIx32, n );
         console.parse( buf );
         return console;
     }
operator<<() [11/13]
Console& libtp::display::operator<< (Console & console, uint64_t n)
Definition at line 181 of file console.cpp.
     {
         return console << static_cast<uint32_t>( n >> 32 ) << static_cast<uint32_t>( n );
     }
operator<<() [12/13]
Console& libtp::display::operator<< (Console & console, uint8_t n)
Definition at line 115 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%02" PRIx8, n );
         console.parse( buf );
         return console;
     }
operator<<() [13/13]
Console& libtp::display::operator<< (Console & console, void * ptr)
Definition at line 203 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "0x%" PRIxPTR, reinterpret_cast<uint32_t>( ptr ) );
         console.parse( buf );
         return console;
     }
print()
char * libtp::display::print (uint8_t line, const char * text)
Copies text to a console line.
Parameters
line The targeted line
text The text to be printed
Returns
The pointer to the console line
Definition at line 267 of file console.cpp.
     {
         // Get the max size minus one, to insure that the last char is always NULL
         std::size_t max = sizeof( tp::jfw_system::ConsoleLine::line ) - 1;
         return strncpy( tp::jfw_system::systemConsole->consoleLine[line].line, text, max );
     }
References libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::line, and libtp::tp::jfw_system::systemConsole.
setConsole()
void libtp::display::setConsole (bool state, uint8_t lines)
Sets the state of the console.
Parameters
state If true: Enabled otherwise disabled
lines Number of lines to enable, 0 to enable the console but hide the lines (max. 25; check: tp/JFWSystem.h)
Definition at line 242 of file console.cpp.
     {
         // Load the console as a local pointer to avoid loading it each loop
         tp::jfw_system::SystemConsole* console = tp::jfw_system::systemConsole;
         console->consoleEnabled = state;
         for ( uint8_t line = 0; line < lines; line++ )
         {
             console->consoleLine[line].showLine = state;
         }
     }
References libtp::tp::jfw_system::SystemConsole::consoleEnabled, libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::showLine, and libtp::tp::jfw_system::systemConsole.
Referenced by libtp::display::Console::Console(), and mod::setScreen().
setConsoleColor()
void libtp::display::setConsoleColor (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)
Sets the console background colour + Alpha.
Definition at line 255 of file console.cpp.
     {
         // Load the console as a local pointer to save memory on each use
         tp::jfw_system::SystemConsole* console = tp::jfw_system::systemConsole;
         console->consoleColor[0] = red;
         console->consoleColor[1] = green;
         console->consoleColor[2] = blue;
         console->consoleColor[3] = alpha;
         return;
     }
References libtp::tp::jfw_system::SystemConsole::consoleColor, and libtp::tp::jfw_system::systemConsole.