Twilight Princess Randomizer [GC]: mod Namespace Reference
mod Namespace Reference
Namespaces
events
game_patch
rando
Functions
void main ()
void hookFunctions ()
void setScreen (bool state)
void handleInput (uint32_t inputs)
void handle_fapGm_Execute (void)
bool handle_do_Link (libtp::tp::dynamic_link::DynamicModuleControl *dmc)
libtp::display::Console console (9)
void doInput (uint32_t input)
Variables
libtp::display::Console console
rando::Randomizer * randomizer = nullptr
rando::SeedList * seedList = nullptr
uint32_t lastButtonInput = 0
int32_t lastLoadingState = 0
bool consoleState = true
uint8_t gameState = GAME_BOOT
void(* return_fapGm_Execute)(void) = nullptr
bool(* return_do_Link)(libtp::tp::dynamic_link::DynamicModuleControl *dmc) = nullptr
bool(* return_actorInit)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) = nullptr
bool(* return_actorInit_always)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) = nullptr
bool(* return_actorCommonLayerInit)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) = nullptr
Function Documentation
console()
libtp::display::Console mod::console (9)
doInput()
void mod::doInput (uint32_t input)
Definition at line 113 of file main.cpp.
     {
         using namespace libtp::tp::m_do_controller_pad;
         auto checkBtn = [&input]( uint32_t combo ) { return ( input & combo ) == combo; };
         if ( input && gameState == GAME_TITLE )
         {
             // Handle seed selection if necessary
             if ( seedList->m_numSeeds > 1 )
             {
                 if ( checkBtn( Button_X ) )
                 {
                     seedList->m_selectedSeed++;
                     if ( seedList->m_selectedSeed >= seedList->m_numSeeds )
                         seedList->m_selectedSeed = 0;
                 }
                 else if ( checkBtn( Button_Y ) )
                 {
                     if ( seedList->m_selectedSeed == 0 )
                         seedList->m_selectedSeed = seedList->m_numSeeds;
                     seedList->m_selectedSeed--;
                 }
                 // 8 is the line it typically appears
                 console.setLine( 8 );
                 console << "\r"
                         << "[" << seedList->m_selectedSeed + 1 << "/" << seedList->m_numSeeds
                         << "] Seed: " << seedList->m_seedInfo[seedList->m_selectedSeed].header.seed << "\n";
             }
         }
         // End of handling title screen inputs
     }
References console, gameState, mod::rando::SeedInfo::header, mod::rando::SeedList::m_numSeeds, mod::rando::SeedList::m_seedInfo, mod::rando::SeedList::m_selectedSeed, mod::rando::Header::seed, seedList, and libtp::display::Console::setLine().
Referenced by handle_fapGm_Execute().
handle_do_Link()
bool mod::handle_do_Link (libtp::tp::dynamic_link::DynamicModuleControl * dmc)
Definition at line 270 of file main.cpp.
     {
         // Call the original function immediately, as the REL file needs to be linked before applying patches
         const bool result = return_do_Link( dmc );
         // TODO: Implementation of dynamic module overrides
         return result;
     }
References return_do_Link.
Referenced by hookFunctions().
handle_fapGm_Execute()
void mod::handle_fapGm_Execute (void)
Definition at line 148 of file main.cpp.
     {
         using namespace libtp;
         using namespace tp::m_do_controller_pad;
         using namespace tp::d_com_inf_game;
         // Load relevant pointers locally for faster access
         CPadInfo* padInfo = &cpadInfo;
         GameInfo* gameInfo = &dComIfG_gameInfo;
         // Handle game state updates
         using namespace libtp::tp::f_pc_node_req;
         if ( l_fpcNdRq_Queue )
         {
             // Previous state
             uint8_t prevState = gameState;
             uint8_t state = *reinterpret_cast<uint8_t*>( reinterpret_cast<uint32_t>( l_fpcNdRq_Queue ) + 0x59 );
             // Normal/Loading into game
             if ( prevState != GAME_ACTIVE && state == 11 )
             {
                 // check whether we're in title screen CS
                 if ( 0 != strcmp( "S_MV000", gameInfo->nextStageVars.nextStage ) )
                 {
                     gameState = GAME_ACTIVE;
                 }
             }
             else if ( prevState != GAME_TITLE && ( state == 12 || state == 13 ) )
             {
                 gameState = GAME_TITLE;
                 // Handle console differently when the user first loads it
                 if ( prevState == GAME_BOOT )
                 {
                     switch ( seedList->m_numSeeds )
                     {
                         case 0:
                             // Err, no seeds
                             console << "No seeds available! Please check your memory card and region!\n";
                             setScreen( true );
                             break;
                         case 1:
                             // Only one seed present, auto-select it and disable console for convenience
                             console << "First and only seed automatically applied...\n";
                             setScreen( false );
                             break;
                         default:
                             // User has to select one of the seeds
                             console << "Please select a seed <X/Y>\n";
                             // trigger a dummy input to print the current selection
                             doInput( Button_Start );
                             setScreen( true );
                             break;
                     }
                 }
             }
         }
         // End of handling gameStates
         // handle button inputs only if buttons are being held that weren't held last time
         if ( padInfo->buttonInput != lastButtonInput )
         {
             // Store before processing since we (potentially) un-set the padInfo values later
             lastButtonInput = padInfo->buttonInput;
             // Special combo to (de)activate the console should be handled first
             if ( ( padInfo->buttonInput & ( PadInputs::Button_R | PadInputs::Button_Z ) ) ==
                  ( PadInputs::Button_R | PadInputs::Button_Z ) )
             {
                 // Disallow during boot as we print copyright info etc.
                 // Will automatically disappear if there is no seeds to select from
                 setScreen( !consoleState || gameState == GAME_BOOT );
             }
             // Handle Inputs if console is already active
             else if ( consoleState )
             {
                 doInput( padInfo->buttonInput );
                 // Disable input so game doesn't notice
                 padInfo->buttonInput = 0;
                 padInfo->buttonInputTrg = 0;
             }
         }
         // Handle rando state
         if ( gameState == GAME_ACTIVE )
         {
             if ( seedList->m_numSeeds > 0 && !randomizer && !tp::f_op_scene_req::isLoading )
             {
                 randomizer = new rando::Randomizer( &seedList->m_seedInfo[seedList->m_selectedSeed] );
             }
         }
         else if ( randomizer )
         {
             delete randomizer;
             randomizer = nullptr;
         }
         // Custom events
         if ( !lastLoadingState && tp::f_op_scene_req::isLoading )
         {
             // OnLoad
             events::onLoad( randomizer );
         }
         if ( lastLoadingState && !tp::f_op_scene_req::isLoading )
         {
             // OffLoad
             events::offLoad( randomizer );
         }
         lastLoadingState = tp::f_op_scene_req::isLoading;
         // End of custom events
         return return_fapGm_Execute();
     }
References libtp::tp::m_do_controller_pad::Button_R, libtp::tp::m_do_controller_pad::Button_Start, libtp::tp::m_do_controller_pad::Button_Z, libtp::tp::m_do_controller_pad::CPadInfo::buttonInput, libtp::tp::m_do_controller_pad::CPadInfo::buttonInputTrg, console, consoleState, libtp::tp::m_do_controller_pad::cpadInfo, libtp::tp::d_com_inf_game::dComIfG_gameInfo, doInput(), gameState, libtp::tp::f_op_scene_req::isLoading, libtp::tp::f_pc_node_req::l_fpcNdRq_Queue, lastButtonInput, lastLoadingState, mod::rando::SeedList::m_numSeeds, mod::rando::SeedList::m_seedInfo, mod::rando::SeedList::m_selectedSeed, libtp::tp::d_com_inf_game::NextStageVars::nextStage, libtp::tp::d_com_inf_game::GameInfo::nextStageVars, mod::events::offLoad(), mod::events::onLoad(), mod::rando::Randomizer::Randomizer(), randomizer, return_fapGm_Execute, seedList, and setScreen().
Referenced by hookFunctions().
handleInput()
void mod::handleInput (uint32_t inputs)
hookFunctions()
void mod::hookFunctions ()
Definition at line 72 of file main.cpp.
     {
         using namespace libtp;
         using namespace libtp::tp::d_stage;
         using namespace libtp::tp::dzx;
         // Hook functions
         return_fapGm_Execute = patch::hookFunction( libtp::tp::f_ap_game::fapGm_Execute, mod::handle_fapGm_Execute );
         return_do_Link = patch::hookFunction( libtp::tp::dynamic_link::do_link, handle_do_Link );
         // DZX
         return_actorInit =
             patch::hookFunction( actorInit,
                                  []( void* mStatus_roomControl, ChunkTypeInfo* chunkTypeInfo, int32_t unk3, void* unk4 )
{
                                      events::onDZX( mod::randomizer, chunkTypeInfo );
                                      return return_actorInit( mStatus_roomControl, chunkTypeInfo, unk3, unk4 );
                                  } );
         return_actorInit_always =
             patch::hookFunction( actorInit_always,
                                  []( void* mStatus_roomControl, ChunkTypeInfo* chunkTypeInfo, int32_t unk3, void* unk4 )
{
                                      events::onDZX( mod::randomizer, chunkTypeInfo );
                                      return return_actorInit_always( mStatus_roomControl, chunkTypeInfo, unk3, unk4 );
                                  } );
         return_actorCommonLayerInit =
             patch::hookFunction( actorCommonLayerInit,
                                  []( void* mStatus_roomControl, ChunkTypeInfo* chunkTypeInfo, int32_t unk3, void* unk4 )
{
                                      events::onDZX( mod::randomizer, chunkTypeInfo );
                                      return return_actorCommonLayerInit( mStatus_roomControl, chunkTypeInfo, unk3, unk4 );
                                  } );
     }
References libtp::tp::d_stage::actorCommonLayerInit(), libtp::tp::d_stage::actorInit(), libtp::tp::d_stage::actorInit_always(), libtp::tp::dynamic_link::do_link(), libtp::tp::f_ap_game::fapGm_Execute(), handle_do_Link(), handle_fapGm_Execute(), libtp::patch::hookFunction(), mod::events::onDZX(), randomizer, return_actorCommonLayerInit, return_actorInit, return_actorInit_always, return_do_Link, and return_fapGm_Execute.
Referenced by main().
main()
void mod::main ()
Definition at line 55 of file main.cpp.
     {
         // Display some info
         console << "Welcome to TPR!\n"
                 << "(C) AECX, Lunar Soap, Zephiles\n\n"
                 << "Note:\n"
                 << "Please avoid [re]starting rando unnecessarily\n"
                 << "on ORIGINAL HARDWARE as it wears down your\n"
                 << "Memory Card!\n\n";
         // Just hook functions for now
         hookFunctions();
         // Generate our seedList
         seedList = new rando::SeedList();
     }
References console, hookFunctions(), mod::rando::SeedList::SeedList(), and seedList.
Referenced by _prolog().
setScreen()
void mod::setScreen (bool state)
Definition at line 107 of file main.cpp.
     {
         consoleState = state;
         libtp::display::setConsole( state, 0 );
     }
References consoleState, and libtp::display::setConsole().
Referenced by handle_fapGm_Execute().
Variable Documentation
console
libtp::display::Console mod::console(9)
Referenced by doInput(), handle_fapGm_Execute(), mod::rando::Seed::InitSeed(), main(), mod::rando::Randomizer::onStageLoad(), mod::game_patch::patchWallet(), mod::rando::Randomizer::Randomizer(), mod::rando::Seed::Seed(), mod::rando::SeedList::SeedList(), and mod::rando::Randomizer::~Randomizer().
consoleState
bool mod::consoleState = true
Definition at line 32 of file main.cpp.
Referenced by handle_fapGm_Execute(), and setScreen().
gameState
uint8_t mod::gameState = GAME_BOOT
Definition at line 33 of file main.cpp.
Referenced by doInput(), and handle_fapGm_Execute().
lastButtonInput
uint32_t mod::lastButtonInput = 0
Definition at line 30 of file main.cpp.
Referenced by handle_fapGm_Execute().
lastLoadingState
int32_t mod::lastLoadingState = 0
Definition at line 31 of file main.cpp.
Referenced by handle_fapGm_Execute().
randomizer
rando::Randomizer * mod::randomizer = nullptr
Definition at line 26 of file main.cpp.
Referenced by handle_fapGm_Execute(), and hookFunctions().
return_actorCommonLayerInit
bool(* mod::return_actorCommonLayerInit)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) (void * mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4) = nullptr
Definition at line 50 of file main.cpp.
Referenced by hookFunctions().
return_actorInit
bool(* mod::return_actorInit)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) (void * mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4) = nullptr
Definition at line 40 of file main.cpp.
Referenced by hookFunctions().
return_actorInit_always
bool(* mod::return_actorInit_always)(void *mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4) (void * mStatus_roomControl, libtp::tp::dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4) = nullptr
Definition at line 45 of file main.cpp.
Referenced by hookFunctions().
return_do_Link
bool(* mod::return_do_Link)(libtp::tp::dynamic_link::DynamicModuleControl *dmc) (libtp::tp::dynamic_link::DynamicModuleControl * dmc) = nullptr
Definition at line 37 of file main.cpp.
Referenced by handle_do_Link(), and hookFunctions().
return_fapGm_Execute
void(* mod::return_fapGm_Execute)(void) (void) = nullptr
Definition at line 36 of file main.cpp.
Referenced by handle_fapGm_Execute(), and hookFunctions().
seedList
rando::SeedList * mod::seedList = nullptr
Definition at line 27 of file main.cpp.
Referenced by doInput(), handle_fapGm_Execute(), and main().