Twilight Princess Randomizer [GC]: libtp::tools Namespace Reference
libtp::tools Namespace Reference
Functions
uint16_t fletcher16 (uint8_t *data, int32_t length)
Fletcher16 checksum.
void TriggerSaveLoad (const char *stage, uint8_t room, uint8_t spawn, uint8_t state=0xFF, uint8_t event=0xFF)
Savely loads a given stage-room-spawnpoint-state and event combination.
void SpawnActor (uint8_t roomID, tp::dzx::ACTR &actor)
Spawns an actor.
int32_t ReadGCI (int32_t chan, const char *fileName, int32_t length, int32_t offset, void *buffer)
Reads GCI data from offset to offset + length into buffer.
Function Documentation
fletcher16()
uint16_t libtp::tools::fletcher16 (uint8_t * data, int32_t length)
Fletcher16 checksum.
Parameters
data Data to calculate the checksum from
length How many bytes of data should be considered
Returns
Checksum in 2 bytes
Definition at line 19 of file tools.cpp.
     {
         uint16_t sum1 = 0;
         uint16_t sum2 = 0;
         for ( int32_t index = 0; index < length; ++index )
         {
             sum1 = ( sum1 + data[index] ) % 0xFF;
             sum2 = ( sum2 + sum1 ) % 0xFF;
         }
         return ( sum2 << 8 ) | sum1;
     }
Referenced by mod::rando::Randomizer::replaceDZX().
ReadGCI()
int32_t libtp::tools::ReadGCI (int32_t chan, const char * fileName, int32_t length, int32_t offset, void * buffer)
Reads GCI data from offset to offset + length into buffer.
Parameters
chan Slot to check for the file
fileName GCI Filename to load
length Maximum length to read
offset GCI fileOffset to read
[out] buffer Buffer to save the data
Returns
One of the CARD_RESULT Constants (CARD_RESULT_READY, ...)
Definition at line 76 of file tools.cpp.
     {
         using namespace libtp::gc::card;
         CARDFileInfo* fileInfo = new CARDFileInfo();
         uint8_t* workArea = new uint8_t[CARD_WORKAREA_SIZE];
         int32_t result;
         // Since we can only read in and at increments of CARD_READ_SIZE do this to calculate the region we require
         int32_t adjustedOffset = ( offset / CARD_READ_SIZE ) * CARD_READ_SIZE;
         int32_t adjustedLength = ( 1 + ( ( offset - adjustedOffset + length - 1 ) / CARD_READ_SIZE ) ) * CARD_READ_SIZE;
         // Buffer might not be adjusted to the new length so create a temporary data buffer
         uint8_t* data = new uint8_t[adjustedLength];
         // Check if card is valid
         result = CARDProbeEx( chan, NULL, NULL );
         if ( result == CARD_RESULT_READY )
         {
             result = CARDMount( chan,
                                 workArea,
                                 []( int32_t chan, int32_t result )
{
                                     // S
                                     tp::jfw_system::ConsoleLine* line =
                                         &tp::jfw_system::systemConsole->consoleLine[JFW_DEBUG_LINE];
                                     line->showLine = true;
                                     sprintf( line->line, "ReadGCI::CARDERR; Chan: %" PRId32 " Result: %" PRId32, chan, result );
                                 } );
             if ( result == CARD_RESULT_READY )
             {
                 // Read data
                 result = CARDOpen( chan, const_cast<char*>( fileName ), fileInfo );
                 if ( result == CARD_RESULT_READY )
                 {
                     result = CARDRead( fileInfo, data, adjustedLength, adjustedOffset );
                     CARDClose( fileInfo );
                     // Copy data to the user's buffer
                     memcpy( buffer, data + ( offset - adjustedOffset ), length );
                 }
                 // CARDOpen
                 CARDUnmount( chan );
             }
             // CARDMount
         }
         // CARDProbeEx
         // Clean up
         delete fileInfo;
         delete[] workArea;
         delete[] data;
         return result;
     }
References libtp::gc::card::CARDClose(), libtp::gc::card::CARDMount(), libtp::gc::card::CARDOpen(), libtp::gc::card::CARDProbeEx(), libtp::gc::card::CARDRead(), libtp::gc::card::CARDUnmount(), libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::line, libtp::tp::jfw_system::ConsoleLine::showLine, and libtp::tp::jfw_system::systemConsole.
Referenced by mod::rando::Seed::InitSeed(), and mod::rando::SeedList::SeedList().
SpawnActor()
void libtp::tools::SpawnActor (uint8_t roomID, tp::dzx::ACTR & actor)
Spawns an actor.
Parameters
roomID Room id to spawn the actor
actor The actor object to be spawned
Definition at line 53 of file tools.cpp.
     {
         using namespace libtp::tp::dzx;
         using namespace libtp::tp::f_op_actor_mng;
         ActorPRMClass* actorMemoryPtr = CreateAppend();
         actorMemoryPtr->params = actor.parameters;
         actorMemoryPtr->pos[0] = actor.pos[0];
         actorMemoryPtr->pos[1] = actor.pos[1];
         actorMemoryPtr->pos[2] = actor.pos[2];
         actorMemoryPtr->xRot = actor.rot[0];
         actorMemoryPtr->yRot = actor.rot[1];
         actorMemoryPtr->flag = actor.flag;
         actorMemoryPtr->enemy_id = actor.enemyID;
         actorMemoryPtr->room_id = roomID;
         tp::d_stage::ActorCreate( &actor, actorMemoryPtr );
     }
References libtp::tp::d_stage::ActorCreate(), libtp::tp::f_op_actor_mng::CreateAppend(), libtp::tp::dzx::ActorPRMClass::enemy_id, libtp::tp::dzx::ACTR::enemyID, libtp::tp::dzx::ACTR::flag, libtp::tp::dzx::ActorPRMClass::flag, libtp::tp::dzx::ACTR::parameters, libtp::tp::dzx::ActorPRMClass::params, libtp::tp::dzx::ACTR::pos, libtp::tp::dzx::ActorPRMClass::pos, libtp::tp::dzx::ActorPRMClass::room_id, libtp::tp::dzx::ACTR::rot, libtp::tp::dzx::ActorPRMClass::xRot, and libtp::tp::dzx::ActorPRMClass::yRot.
TriggerSaveLoad()
void libtp::tools::TriggerSaveLoad (const char * stage, uint8_t room, uint8_t spawn, uint8_t state = 0xFF, uint8_t event = 0xFF)
Savely loads a given stage-room-spawnpoint-state and event combination.
Parameters
stage 8 char stage ID
room Room ID
spawn Spawnpoint
state Current State (Link)
event EventID to trigger
Definition at line 33 of file tools.cpp.
     {
         using namespace libtp::tp::d_com_inf_game;
         GameInfo* gameInfo = &dComIfG_gameInfo;
         strcpy( gameInfo->nextStageVars.nextStage, stage );
         gameInfo->nextStageVars.nextRoom = room;
         gameInfo->nextStageVars.nextSpawnPoint = spawn;
         gameInfo->nextStageVars.nextState = state;
         gameInfo->eventSystem.nextEventID = event;
         gameInfo->respawnAnimation = 0;
         gameInfo->nextStageVars.isVoidorWarp = 0;
         gameInfo->respawnCutscene = 0;
         gameInfo->eventSystem.immediateControl = 0xFFFF;
         gameInfo->nextStageVars.fadeType = 0x13;
         gameInfo->nextStageVars.triggerLoad = true;
     }
References libtp::tp::d_com_inf_game::dComIfG_gameInfo, libtp::tp::d_com_inf_game::GameInfo::eventSystem, libtp::tp::d_com_inf_game::NextStageVars::fadeType, libtp::tp::d_com_inf_game::EventSystem::immediateControl, libtp::tp::d_com_inf_game::NextStageVars::isVoidorWarp, libtp::tp::d_com_inf_game::EventSystem::nextEventID, libtp::tp::d_com_inf_game::NextStageVars::nextRoom, libtp::tp::d_com_inf_game::NextStageVars::nextSpawnPoint, libtp::tp::d_com_inf_game::NextStageVars::nextStage, libtp::tp::d_com_inf_game::GameInfo::nextStageVars, libtp::tp::d_com_inf_game::NextStageVars::nextState, libtp::tp::d_com_inf_game::GameInfo::respawnAnimation, libtp::tp::d_com_inf_game::GameInfo::respawnCutscene, and libtp::tp::d_com_inf_game::NextStageVars::triggerLoad.