Twilight Princess Randomizer [GC]: mod::rando::Seed Class Reference
mod::rando::Seed Class Reference
#include "seed.h"
Public Member Functions
Seed (int32_t chan, SeedInfo *seedInfo)
Class to dynamically load required data from a given seed.
~Seed ()
Deletes all allocated members and unpatches all the previously applied patches.
void InitSeed (void)
Applies patches, event & region flags according to this seed to the current savefile.
bool LoadChecks (const char *stage)
Load check data for a given stage & stores them in a temp. (smaller) buffer.
Public Attributes
int32_t m_CARDResult
uint32_t m_SeedStatus = 0
uint32_t m_PatchesApplied = 0
uint32_t m_EventFlagsModified = 0
uint32_t m_AreaFlagsModified = 0
Header * m_Header = nullptr
uint32_t m_StageIDX = 0xFF
dzxCheck * m_DZXChecks = nullptr
uint32_t m_numLoadedDZXChecks = 0
RELCheck * m_RELChecks = nullptr
uint32_t m_numLoadedRELChecks = 0
Private Member Functions
void ClearChecks (void)
void applyPatches (bool set)
Manages game_patches from the seed.
void applyEventFlags (void)
void applyRegionFlags (void)
void LoadDZX (uint8_t stageIDX)
void LoadREL (uint8_t stageIDX)
Private Attributes
uint8_t * m_GCIData = nullptr
uint8_t m_fileIndex = 0xFF
int32_t m_CardSlot = 0
Detailed Description
Definition at line 25 of file seed.h.
Constructor & Destructor Documentation
Seed()
mod::rando::Seed::Seed (int32_t chan, SeedInfo * seedInfo)
Class to dynamically load required data from a given seed.
Parameters
seedInfo Pointer to the seedinfo that we intend to load
Definition at line 26 of file seed.cpp.
                                                 : m_CardSlot( chan )
     {
         m_Header = &seedInfo->header;
         // Loading seed rando-dataX '<seed>'...
         // Set our filename
         m_fileIndex = seedInfo->fileIndex;
         mod::console << "Loading seed " << m_fileIndex << ": '" << m_Header->seed << "'...\n";
         InitSeed();
     }
References mod::console, mod::rando::SeedInfo::fileIndex, mod::rando::SeedInfo::header, InitSeed(), m_CardSlot, m_fileIndex, m_Header, and mod::rando::Header::seed.
Referenced by mod::rando::Randomizer::Randomizer().
~Seed()
mod::rando::Seed::~Seed ()
Deletes all allocated members and unpatches all the previously applied patches.
Definition at line 40 of file seed.cpp.
     {
         // Make sure to delete tempcheck buffers
         this->ClearChecks();
         // Only work with m_GCIData if the buffer is populated
         if ( m_GCIData )
         {
             this->applyPatches( false );
             // Last clear gcibuffer as other functions before rely on it
             delete[] m_GCIData;
         }
     }
References applyPatches(), ClearChecks(), and m_GCIData.
Member Function Documentation
applyEventFlags()
void mod::rando::Seed::applyEventFlags (void) private
Definition at line 173 of file seed.cpp.
     {
         using namespace libtp;
         m_SeedStatus |= SEED_STATUS_EVENTFLG;
         uint32_t num_eventFlags = m_Header->eventFlagsInfo.numEntries;
         uint32_t gci_offset = m_Header->eventFlagsInfo.dataOffset;
         if ( num_eventFlags > 0 )
         {
             tp::d_com_inf_game::GameInfo* gameInfo = &tp::d_com_inf_game::dComIfG_gameInfo;
             // Set the pointer as offset into our buffer
             eventFlag* eventFlags = reinterpret_cast<eventFlag*>( &m_GCIData[gci_offset] );
             for ( uint32_t i = 0; i < num_eventFlags; i++ )
             {
                 uint8_t offset = eventFlags[i].offset;
                 uint8_t flag = eventFlags[i].flag;
                 gameInfo->scratchPad.eventBits[offset] |= flag;
                 m_EventFlagsModified++;
             }
         }
     }
References mod::rando::entryInfo::dataOffset, libtp::tp::d_com_inf_game::dComIfG_gameInfo, libtp::tp::d_com_inf_game::ScratchPad::eventBits, mod::rando::Header::eventFlagsInfo, mod::rando::eventFlag::flag, m_EventFlagsModified, m_GCIData, m_Header, m_SeedStatus, mod::rando::entryInfo::numEntries, mod::rando::eventFlag::offset, and libtp::tp::d_com_inf_game::GameInfo::scratchPad.
Referenced by InitSeed().
applyPatches()
void mod::rando::Seed::applyPatches (bool set) private
Manages game_patches from the seed.
Parameters
set If true it will set the patches, otherwise restore the original
Definition at line 133 of file seed.cpp.
     {
         using namespace libtp;
         m_SeedStatus |= SEED_STATUS_PATCHED;
         uint32_t num_patches = m_Header->patchInfo.numEntries;
         uint32_t gci_offset = m_Header->patchInfo.dataOffset;
         // Don't bother to patch anything if there's nothing to patch
         if ( num_patches > 0 )
         {
             uint32_t num_bytes = num_patches / 8 + 1;
             // Set the pointer as offset into our buffer
             uint8_t* patch_config = &m_GCIData[gci_offset];
             for ( uint32_t i = 0; i < num_bytes; i++ )
             {
                 uint8_t byte = patch_config[i];
                 for ( uint32_t b = 0; b < 8; b++ )
                 {
                     if ( ( byte >> b ) & 0x80 )
                     {
                         // run the patch function for this bit index
                         uint32_t index = i * 8 + b;
                         using namespace game_patch;
                         if ( index < sizeof( patches ) / sizeof( patches[0] ) )
{
                             patches[index]( set );
                             m_PatchesApplied++;
                         }
                     }
                 }
             }
         }
     }
References mod::rando::entryInfo::dataOffset, m_GCIData, m_Header, m_PatchesApplied, m_SeedStatus, mod::rando::entryInfo::numEntries, mod::game_patch::patches, and mod::rando::Header::patchInfo.
Referenced by InitSeed(), and ~Seed().
applyRegionFlags()
void mod::rando::Seed::applyRegionFlags (void) private
Definition at line 200 of file seed.cpp.
     {
         using namespace libtp;
         m_SeedStatus |= SEED_STATUS_REGIONFLG;
         uint32_t num_regionFlags = m_Header->regionFlagsInfo.numEntries;
         uint32_t gci_offset = m_Header->regionFlagsInfo.dataOffset;
         if ( num_regionFlags > 0 )
         {
             tp::d_com_inf_game::GameInfo* gameInfo = &tp::d_com_inf_game::dComIfG_gameInfo;
             // Set the pointer as offset into our buffer
             regionFlag* regionFlags = reinterpret_cast<regionFlag*>( &m_GCIData[gci_offset] );
             uint8_t regionID = data::stage::regions[0];
             // Loop through all regions
             for ( uint32_t i = 0; i < sizeof( data::stage::regions ); i++ )
             {
                 regionID = data::stage::regions[i];
                 tp::d_save::getSave( gameInfo, regionID );
                 // Loop through region-flags from gci
                 for ( uint32_t j = 0; j < num_regionFlags; j++ )
                 {
                     if ( regionFlags[j].region_id == regionID )
                     {
                         // The n'th bit that we want to set TRUE
                         int32_t bit = regionFlags[j].bit_id;
                         int32_t offset = bit / 8;
                         int32_t shift = bit % 8;
                         // Failsafe; localAreaNode size is 0x20
                         if ( offset < 0x20 )
{
                             gameInfo->localAreaNodes[offset] |= ( 0x80 >> shift );
                             m_AreaFlagsModified++;
                         }
                     }
                 }
                 // Save the modifications
                 tp::d_save::putSave( gameInfo, regionID );
             }
             // Reset to previous region ID
             uint8_t i = 0;
             while ( !strcmp( data::stage::allStages[i], gameInfo->currentStage ) )
             {
                 i++;
             }
             tp::d_save::getSave( gameInfo, data::stage::regions[i] );
         }
     }
References libtp::data::stage::allStages, mod::rando::regionFlag::bit_id, libtp::tp::d_com_inf_game::GameInfo::currentStage, mod::rando::entryInfo::dataOffset, libtp::tp::d_com_inf_game::dComIfG_gameInfo, libtp::tp::d_save::getSave(), libtp::tp::d_com_inf_game::GameInfo::localAreaNodes, m_AreaFlagsModified, m_GCIData, m_Header, m_SeedStatus, mod::rando::entryInfo::numEntries, libtp::tp::d_save::putSave(), mod::rando::regionFlag::region_id, mod::rando::Header::regionFlagsInfo, and libtp::data::stage::regions.
Referenced by InitSeed().
ClearChecks()
void mod::rando::Seed::ClearChecks (void) private
Definition at line 124 of file seed.cpp.
     {
         m_numLoadedDZXChecks = 0;
         m_numLoadedRELChecks = 0;
         delete[] m_DZXChecks;
         delete[] m_RELChecks;
     }
References m_DZXChecks, m_numLoadedDZXChecks, m_numLoadedRELChecks, and m_RELChecks.
Referenced by LoadChecks(), and ~Seed().
InitSeed()
void mod::rando::Seed::InitSeed (void)
Applies patches, event & region flags according to this seed to the current savefile.
Definition at line 55 of file seed.cpp.
     {
         // (Re)set counters & status
         m_SeedStatus = 0;
         m_AreaFlagsModified = 0;
         m_EventFlagsModified = 0;
         m_PatchesApplied = 0;
         m_SeedStatus |= SEED_STATUS_INITIALIZED;
         // Load the whole gci locally to reduce number of reads (memcard)
         uint32_t length = m_Header->fileSize;
         char fileName[12] = "rando-data\0";
         fileName[10] = static_cast<char>( '0' + m_fileIndex );
         m_GCIData = new uint8_t[length];
         m_CARDResult = libtp::tools::ReadGCI( m_CardSlot, fileName, length, 0x00, m_GCIData );
         if ( m_CARDResult == CARD_RESULT_READY )
         {
             mod::console << "Patching game:\n";
             this->applyPatches( true );
             mod::console << "Event Flags: \n";
             this->applyEventFlags();
             mod::console << "Region Flags: \n";
             this->applyRegionFlags();
         }
         else
         {
             mod::console << "FATAL: Couldn't read Seed #" << m_fileIndex << "\n";
             mod::console << "ERROR: " << m_CARDResult << "\n";
         }
     }
References applyEventFlags(), applyPatches(), applyRegionFlags(), mod::console, mod::rando::Header::fileSize, m_AreaFlagsModified, m_CARDResult, m_CardSlot, m_EventFlagsModified, m_fileIndex, m_GCIData, m_Header, m_PatchesApplied, m_SeedStatus, and libtp::tools::ReadGCI().
Referenced by Seed().
LoadChecks()
bool mod::rando::Seed::LoadChecks (const char * stage)
Load check data for a given stage & stores them in a temp. (smaller) buffer.
Returns
True if checks have been updated (new stage) otherwise we are still on the same stage
Definition at line 94 of file seed.cpp.
     {
         using namespace libtp;
         // Find the index of this stage
         uint8_t stageIDX;
         for ( stageIDX = 0; stageIDX < sizeof( data::stage::allStages ) / sizeof( data::stage::allStages[0] ); stageIDX++ )
         {
             if ( !strcmp( stage, data::stage::allStages[stageIDX] ) )
             {
                 break;
             }
         }
         // Don't run if this isn't actually a new stage
         bool result = stageIDX != m_StageIDX;
         if ( result )
         {
             this->ClearChecks();
             this->LoadDZX( stageIDX );
             this->LoadREL( stageIDX );
             // Save current stageIDX for next time
             m_StageIDX = stageIDX;
         }
         return result;
     }
References libtp::data::stage::allStages, ClearChecks(), LoadDZX(), LoadREL(), and m_StageIDX.
Referenced by mod::rando::Randomizer::onStageLoad().
LoadDZX()
void mod::rando::Seed::LoadDZX (uint8_t stageIDX) private
Definition at line 260 of file seed.cpp.
     {
         using namespace libtp;
         m_SeedStatus |= SEED_STATUS_DZXLOAD;
         uint32_t num_dzxchecks = m_Header->dzxCheckInfo.numEntries;
         uint32_t gci_offset = m_Header->dzxCheckInfo.dataOffset;
         // Set the pointer as offset into our buffer
         dzxCheck* allDZX = reinterpret_cast<dzxCheck*>( &m_GCIData[gci_offset] );
         for ( uint32_t i = 0; i < num_dzxchecks; i++ )
         {
             if ( allDZX[i].stageIDX == stageIDX )
             {
                 m_numLoadedDZXChecks++;
             }
         }
         // Allocate memory the actual RELChecks
         // We do NOT have to clear the previous buffer as that's already done in "LoadChecks()"
         m_DZXChecks = new dzxCheck[m_numLoadedDZXChecks];
         // offset into m_DZXChecks
         uint32_t j = 0;
         for ( uint32_t i = 0; i < num_dzxchecks; i++ )
         {
             if ( allDZX[i].stageIDX == stageIDX )
             {
                 // Store the i'th DZX check into the j'th Loaded DZX check that's relevant to our current stage
                 memcpy( &m_DZXChecks[j], &allDZX[i], sizeof( dzxCheck ) );
                 j++;
             }
         }
     }
References mod::rando::entryInfo::dataOffset, mod::rando::Header::dzxCheckInfo, m_DZXChecks, m_GCIData, m_Header, m_numLoadedDZXChecks, m_SeedStatus, mod::rando::entryInfo::numEntries, and mod::rando::dzxCheck::stageIDX.
Referenced by LoadChecks().
LoadREL()
void mod::rando::Seed::LoadREL (uint8_t stageIDX) private
Definition at line 298 of file seed.cpp.
     {
         using namespace libtp;
         m_SeedStatus |= SEED_STATUS_RELLOAD;
         uint32_t num_relchecks = m_Header->relCheckInfo.numEntries;
         uint32_t gci_offset = m_Header->relCheckInfo.dataOffset;
         // Set the pointer as offset into our buffer
         RELCheck* allREL = reinterpret_cast<RELCheck*>( &m_GCIData[gci_offset] );
         for ( uint32_t i = 0; i < num_relchecks; i++ )
         {
             if ( allREL[i].stageIDX == stageIDX )
             {
                 m_numLoadedRELChecks++;
             }
         }
         // Allocate memory to the actual RELChecks
         // Do NOT need to clear the previous buffer as that's taken care of by LoadChecks()
         m_RELChecks = new RELCheck[m_numLoadedRELChecks];
         // offset into m_RELChecks
         uint32_t j = 0;
         for ( uint32_t i = 0; i < num_relchecks; i++ )
         {
             if ( allREL[i].stageIDX == stageIDX )
             {
                 // Store the i'th DZX check into the j'th Loaded DZX check that's relevant to our current stage
                 memcpy( &m_RELChecks[j], &allREL[i], sizeof( RELCheck ) );
                 j++;
             }
         }
     }
References mod::rando::entryInfo::dataOffset, m_GCIData, m_Header, m_numLoadedRELChecks, m_RELChecks, m_SeedStatus, mod::rando::entryInfo::numEntries, mod::rando::Header::relCheckInfo, and mod::rando::RELCheck::stageIDX.
Referenced by LoadChecks().
Member Data Documentation
m_AreaFlagsModified
uint32_t mod::rando::Seed::m_AreaFlagsModified = 0
Definition at line 34 of file seed.h.
Referenced by applyRegionFlags(), and InitSeed().
m_CARDResult
int32_t mod::rando::Seed::m_CARDResult
Definition at line 29 of file seed.h.
Referenced by InitSeed().
m_CardSlot
int32_t mod::rando::Seed::m_CardSlot = 0 private
Definition at line 74 of file seed.h.
Referenced by InitSeed(), and Seed().
m_DZXChecks
dzxCheck* mod::rando::Seed::m_DZXChecks = nullptr
Definition at line 39 of file seed.h.
Referenced by ClearChecks(), LoadDZX(), and mod::rando::Randomizer::replaceDZX().
m_EventFlagsModified
uint32_t mod::rando::Seed::m_EventFlagsModified = 0
Definition at line 33 of file seed.h.
Referenced by applyEventFlags(), and InitSeed().
m_fileIndex
uint8_t mod::rando::Seed::m_fileIndex = 0xFF private
Definition at line 73 of file seed.h.
Referenced by InitSeed(), and Seed().
m_GCIData
uint8_t* mod::rando::Seed::m_GCIData = nullptr private
Definition at line 72 of file seed.h.
Referenced by applyEventFlags(), applyPatches(), applyRegionFlags(), InitSeed(), LoadDZX(), LoadREL(), and ~Seed().
m_Header
Header* mod::rando::Seed::m_Header = nullptr
Definition at line 36 of file seed.h.
Referenced by applyEventFlags(), applyPatches(), applyRegionFlags(), InitSeed(), LoadDZX(), LoadREL(), and Seed().
m_numLoadedDZXChecks
uint32_t mod::rando::Seed::m_numLoadedDZXChecks = 0
Definition at line 40 of file seed.h.
Referenced by ClearChecks(), LoadDZX(), mod::rando::Randomizer::onStageLoad(), and mod::rando::Randomizer::replaceDZX().
m_numLoadedRELChecks
uint32_t mod::rando::Seed::m_numLoadedRELChecks = 0
Definition at line 43 of file seed.h.
Referenced by ClearChecks(), and LoadREL().
m_PatchesApplied
uint32_t mod::rando::Seed::m_PatchesApplied = 0
Definition at line 32 of file seed.h.
Referenced by applyPatches(), and InitSeed().
m_RELChecks
RELCheck* mod::rando::Seed::m_RELChecks = nullptr
Definition at line 42 of file seed.h.
Referenced by ClearChecks(), and LoadREL().
m_SeedStatus
uint32_t mod::rando::Seed::m_SeedStatus = 0
Definition at line 30 of file seed.h.
Referenced by applyEventFlags(), applyPatches(), applyRegionFlags(), InitSeed(), LoadDZX(), and LoadREL().
m_StageIDX
uint32_t mod::rando::Seed::m_StageIDX = 0xFF
Definition at line 37 of file seed.h.
Referenced by LoadChecks().
The documentation for this class was generated from the following files:
include/rando/seed.h
source/rando/seed.cpp