Twilight Princess Randomizer [GC]: mod::rando::Randomizer Class Reference
mod::rando::Randomizer Class Reference
#include "randomizer.h"
Public Member Functions
Randomizer (SeedInfo *seedInfo)
~Randomizer ()
void onStageLoad (void)
void replaceDZX (libtp::tp::dzx::ChunkTypeInfo *chunkTypeInfo)
Private Attributes
Seed * m_Seed
Detailed Description
Definition at line 19 of file randomizer.h.
Constructor & Destructor Documentation
Randomizer()
mod::rando::Randomizer::Randomizer (SeedInfo * seedInfo)
TODO: Since this runs AFTER the initial load (because questlog etc. has to be avialable for the seed to manipulate it; event flags, region flags, etc.) the initially loaded area/stage will NOT have modified DZX thus rando appears to be disabled workaround would be to simply leave and re-enter the area; Also for new files this doesn't matter because of the intro cutscene.
Definition at line 21 of file randomizer.cpp.
     {
         mod::console << "Rando loading...\n";
         if ( seedInfo->fileIndex == 0xFF )
         {
             mod::console << "<Randomizer> Error: No such seed (0xFF)\n";
         }
         else
         {
             mod::console << "Seed: " << seedInfo->header.seed << "\n";
             m_Seed = new Seed( CARD_SLOT_A, seedInfo );
         }
     }
References mod::console, mod::rando::SeedInfo::fileIndex, mod::rando::SeedInfo::header, m_Seed, mod::rando::Header::seed, and mod::rando::Seed::Seed().
Referenced by mod::handle_fapGm_Execute().
~Randomizer()
mod::rando::Randomizer::~Randomizer (void)
Definition at line 46 of file randomizer.cpp.
     {
         mod::console << "Rando unloading...\n";
         // Clear Seed
         delete m_Seed;
     }
References mod::console, and m_Seed.
Member Function Documentation
onStageLoad()
void mod::rando::Randomizer::onStageLoad (void)
Definition at line 54 of file randomizer.cpp.
     {
         const char* stage = libtp::tp::d_com_inf_game::dComIfG_gameInfo.nextStageVars.nextStage;
         if ( m_Seed->LoadChecks( stage ) )
         {
             int32_t numDZX = m_Seed->m_numLoadedDZXChecks;
             mod::console << numDZX << " Checks loaded for " << stage << "\n";
         }
     }
References mod::console, libtp::tp::d_com_inf_game::dComIfG_gameInfo, mod::rando::Seed::LoadChecks(), mod::rando::Seed::m_numLoadedDZXChecks, m_Seed, libtp::tp::d_com_inf_game::NextStageVars::nextStage, and libtp::tp::d_com_inf_game::GameInfo::nextStageVars.
Referenced by mod::events::onLoad().
replaceDZX()
void mod::rando::Randomizer::replaceDZX (libtp::tp::dzx::ChunkTypeInfo * chunkTypeInfo)
Definition at line 66 of file randomizer.cpp.
     {
         // Local vars
         uint32_t numReplacements = m_Seed->m_numLoadedDZXChecks;
         dzxCheck* dzxReplacements = m_Seed->m_DZXChecks;
         uint32_t numChunks = chunkTypeInfo->numChunks;
         libtp::tp::dzx::ACTR* dzxData = reinterpret_cast<libtp::tp::dzx::ACTR*>( chunkTypeInfo->chunkDataPtr );
         // Check if we have DZX checks to work with
         if ( !numReplacements )
             return;
         // Loop through all chunks the game is currently loading/setting
         for ( uint32_t i = 0; i < numChunks; i++ )
         {
             // The hash in RAM right now
             uint16_t actorHash =
                 libtp::tools::fletcher16( reinterpret_cast<uint8_t*>( &dzxData[i] ), sizeof( libtp::tp::dzx::ACTR ) );
             // Compare to all available replacements
             for ( uint32_t j = 0; j < numReplacements; j++ )
             {
                 if ( dzxReplacements[j].hash == actorHash )
                 {
                     // Bytearray of target ACTR struct
                     uint8_t* target = reinterpret_cast<uint8_t*>( &dzxData[i] );
                     // Replace target Actor with replacement values if != FF
                     for ( uint8_t b = 0; b < sizeof( libtp::tp::dzx::ACTR ); b++ )
                     {
                         // Fetch replacement byte
                         uint8_t newByte = dzxReplacements[j].data[b];
                         if ( newByte != 0xFF )
                             target[b] = newByte;
                     }
                 }
             }
         }
     }
References libtp::tp::dzx::ChunkTypeInfo::chunkDataPtr, mod::rando::dzxCheck::data, libtp::tools::fletcher16(), mod::rando::dzxCheck::hash, mod::rando::Seed::m_DZXChecks, mod::rando::Seed::m_numLoadedDZXChecks, m_Seed, and libtp::tp::dzx::ChunkTypeInfo::numChunks.
Referenced by mod::events::onDZX().
Member Data Documentation
m_Seed
Seed* mod::rando::Randomizer::m_Seed private
Definition at line 29 of file randomizer.h.
Referenced by onStageLoad(), Randomizer(), replaceDZX(), and ~Randomizer().
The documentation for this class was generated from the following files:
include/rando/randomizer.h
source/rando/randomizer.cpp