Twilight Princess Randomizer [GC]: libtp::tp::d_stage Namespace Reference
libtp::tp::d_stage Namespace Reference
Functions
void setTresure (void *unk1)
void roomTresureInit (void *unk1, dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4)
Initialises TRES for a given room.
bool actorCommonLayerInit (void *mStatus_roomControl, dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4)
Initialises Actors, can run multiple times per load - Global Based on Room.
bool actorInit (void *mStatus_roomControl, dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4)
Initialises Actors for current layer, can run multiple times per load.
bool actorInit_always (void *mStatus_roomControl, dzx::ChunkTypeInfo *chunkTypeInfo, int32_t unk3, void *unk4)
Initialises Actors for global layer, can run multiple times per load.
void ActorCreate (dzx::ACTR *actor, dzx::ActorPRMClass *actorMemoryPtr)
Creates an actor.
Variables
void * mStatus_roomControl
Pointer to roomControl data.
Function Documentation
actorCommonLayerInit()
bool libtp::tp::d_stage::actorCommonLayerInit (void * mStatus_roomControl, dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4)
Initialises Actors, can run multiple times per load - Global Based on Room.
Parameters
mStatus_roomControl Pointer to roomControl data (unknown)
chunkTypeInfo Pointer to dzxHeader
unk3 unknown
unk4 unknown
Referenced by mod::hookFunctions().
ActorCreate()
void libtp::tp::d_stage::ActorCreate (dzx::ACTR * actor, dzx::ActorPRMClass * actorMemoryPtr)
Creates an actor.
Parameters
Actor Actor Object
ActorMemoryPtr ActorPRMClass allocated for this Actor
Referenced by libtp::tools::SpawnActor().
actorInit()
bool libtp::tp::d_stage::actorInit (void * mStatus_roomControl, dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4)
Initialises Actors for current layer, can run multiple times per load.
Parameters
mStatus_roomControl Pointer to roomControl data (unknown)
chunkTypeInfo Pointer to dzxHeader
unk3 unknown
unk4 unknown
Referenced by mod::hookFunctions().
actorInit_always()
bool libtp::tp::d_stage::actorInit_always (void * mStatus_roomControl, dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4)
Initialises Actors for global layer, can run multiple times per load.
Parameters
mStatus_roomControl Pointer to roomControl data (unknown)
chunkTypeInfo Pointer to dzxHeader
unk3 unknown
unk4 unknown
Referenced by mod::hookFunctions().
roomTresureInit()
void libtp::tp::d_stage::roomTresureInit (void * unk1, dzx::ChunkTypeInfo * chunkTypeInfo, int32_t unk3, void * unk4)
Initialises TRES for a given room.
Parameters
chunkTypeInfo Pointer to the TRES chunk metadata
setTresure()
void libtp::tp::d_stage::setTresure (void * unk1)
@brief Used for treasure initialisation (not just chests)
@return Returns the maximum number of rupees Link can hold in his
current wallet
Variable Documentation
mStatus_roomControl
void* libtp::tp::d_stage::mStatus_roomControl extern
Pointer to roomControl data.