Twilight Princess Randomizer [GC]: libtp::display::Console Class Reference
libtp::display::Console Class Reference
Console wrapper class.
#include "console.h"
Public Member Functions
Console (uint8_t protection)
Simple console class.
void parse (const char *text)
Reads a string and outputs it directly.
void setLine (uint8_t line)
Sets the console to a specific line.
Private Attributes
uint8_t m_Line
uint8_t m_Col
uint8_t m_Protect
Friends
Console & operator<< (Console &console, const char *text)
Console & operator<< (Console &console, char *text)
Console & operator<< (Console &console, char chr)
Console & operator<< (Console &console, uint8_t n)
Console & operator<< (Console &console, uint16_t n)
Console & operator<< (Console &console, uint32_t n)
Console & operator<< (Console &console, uint64_t n)
Console & operator<< (Console &console, int8_t n)
Console & operator<< (Console &console, int16_t n)
Console & operator<< (Console &console, int32_t n)
Console & operator<< (Console &console, int64_t n)
Console & operator<< (Console &console, float n)
Console & operator<< (Console &console, void *ptr)
Detailed Description
Console wrapper class.
Todo:
Add features (menu, watches, etc.)
Definition at line 24 of file console.h.
Constructor & Destructor Documentation
Console()
libtp::display::Console::Console (uint8_t protection)
Simple console class.
Warning: This is NOT a proper output buffer like cout! This is just meant for easier access to the console and isn't as feature rich as a proper cout.
Parameters
protection The number of lines to exclude when flushing the screen
Definition at line 13 of file console.cpp.
                                         : m_Protect( protection )
     {
         // Init
         libtp::display::setConsole( true, 25 );
         this->m_Line = 0;
         this->m_Col = 0;
         // Display initial information, then lock line 1 (could be overwritten manually)
         *this << _PROJECT_NAME " - v" _VERSION " " _VARIANT << "\n"
               << "Powered by github/zsrtp/libtp_rel"
               << "\n"
               << "Created by AECX & Zephiles"
               << "\n"
               << "Build ID: " << _BUILDID << "\n"
               << "Version: " << _VERSION " " _VARIANT "\n\n";
     }
References m_Col, m_Line, m_Protect, and libtp::display::setConsole().
Member Function Documentation
parse()
void libtp::display::Console::parse (const char * text)
Reads a string and outputs it directly.
Parameters
text The char array to be parsed and displayed
Definition at line 31 of file console.cpp.
     {
         // Store the console pointer once
         tp::jfw_system::SystemConsole* console = tp::jfw_system::systemConsole;
         while ( *text != '\0' )
         {
             if ( *text == '\n' )
             {
                 this->m_Col = 0;
                 setLine( m_Line + 1 );
             }
             else if ( *text == '\r' )
             {
                 this->m_Col = 0;
             }
             else
             {
                 // Adjust if otherwise out of bounds
                 if ( this->m_Col >= 48 )
                 {
                     // Null terminate this line
                     console->consoleLine[this->m_Line].line[this->m_Col] = '\0';
                     setLine( m_Line + 1 );
                     this->m_Col = 0;
                 }
                 // Print to current line and col
                 console->consoleLine[this->m_Line].line[this->m_Col] = *text;
                 this->m_Col++;
             }
             // Advance the pointer
             text++;
         }     // End of while
         console->consoleLine[this->m_Line].line[this->m_Col] = '\0';
     }
References libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::line, m_Col, m_Line, setLine(), and libtp::tp::jfw_system::systemConsole.
setLine()
void libtp::display::Console::setLine (uint8_t line)
Sets the console to a specific line.
Parameters
line The line to use (0 based)
Definition at line 71 of file console.cpp.
     {
         tp::jfw_system::SystemConsole* console = tp::jfw_system::systemConsole;
         // Clear following lines
         if ( line < m_Line )
         {
             display::clearConsole( line, 0 );
         }
         m_Line = line;
         if ( this->m_Line >= 25 )
         {
             this->m_Line = 24;
             // Move all lines up by one starting at protected + 1
             for ( uint8_t i = m_Protect + 1; i < 25; i++ )
             {
                 strncpy( console->consoleLine[i - 1].line, console->consoleLine[i].line, 48 );
             }
         }
     }
References libtp::display::clearConsole(), libtp::tp::jfw_system::SystemConsole::consoleLine, libtp::tp::jfw_system::ConsoleLine::line, m_Line, m_Protect, and libtp::tp::jfw_system::systemConsole.
Referenced by mod::doInput(), and parse().
Friends And Related Function Documentation
operator<< [1/13]
Console& operator<< (Console & console, char * text) friend
Definition at line 101 of file console.cpp.
     {
         console.parse( text );
         return console;
     }
operator<< [2/13]
Console& operator<< (Console & console, char chr) friend
Definition at line 107 of file console.cpp.
     {
         char buf[1];
         buf[0] = chr;
         console.parse( buf );
         return console;
     }
operator<< [3/13]
Console& operator<< (Console & console, const char * text) friend
Definition at line 95 of file console.cpp.
     {
         console.parse( text );
         return console;
     }
operator<< [4/13]
Console& operator<< (Console & console, float n) friend
Definition at line 191 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         // Is there a cinttype for float?
         sprintf( buf, "%.4f", n );
         console.parse( buf );
         return console;
     }
operator<< [5/13]
Console& operator<< (Console & console, int16_t n) friend
Definition at line 148 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId16, n );
         console.parse( buf );
         return console;
     }
operator<< [6/13]
Console& operator<< (Console & console, int32_t n) friend
Definition at line 170 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId32, n );
         console.parse( buf );
         return console;
     }
operator<< [7/13]
Console& operator<< (Console & console, int64_t n) friend
Definition at line 186 of file console.cpp.
     {
         return console << static_cast<int32_t>( n >> 32 ) << static_cast<int32_t>( n );
     }
operator<< [8/13]
Console& operator<< (Console & console, int8_t n) friend
Definition at line 126 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%" PRId8, n );
         console.parse( buf );
         return console;
     }
operator<< [9/13]
Console& operator<< (Console & console, uint16_t n) friend
Definition at line 137 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%04" PRIx16, n );
         console.parse( buf );
         return console;
     }
operator<< [10/13]
Console& operator<< (Console & console, uint32_t n) friend
Definition at line 159 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%08" PRIx32, n );
         console.parse( buf );
         return console;
     }
operator<< [11/13]
Console& operator<< (Console & console, uint64_t n) friend
Definition at line 181 of file console.cpp.
     {
         return console << static_cast<uint32_t>( n >> 32 ) << static_cast<uint32_t>( n );
     }
operator<< [12/13]
Console& operator<< (Console & console, uint8_t n) friend
Definition at line 115 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "%02" PRIx8, n );
         console.parse( buf );
         return console;
     }
operator<< [13/13]
Console& operator<< (Console & console, void * ptr) friend
Definition at line 203 of file console.cpp.
     {
         // Custom print this
         char buf[15];
         sprintf( buf, "0x%" PRIxPTR, reinterpret_cast<uint32_t>( ptr ) );
         console.parse( buf );
         return console;
     }
Member Data Documentation
m_Col
uint8_t libtp::display::Console::m_Col private
Definition at line 55 of file console.h.
Referenced by Console(), and parse().
m_Line
uint8_t libtp::display::Console::m_Line private
Definition at line 53 of file console.h.
Referenced by Console(), parse(), and setLine().
m_Protect
uint8_t libtp::display::Console::m_Protect private
Definition at line 57 of file console.h.
Referenced by Console(), and setLine().
The documentation for this class was generated from the following files:
externals/libtp_rel/include/display/console.h
externals/libtp_rel/source/display/console.cpp